# Generated by Django 4.0.3 on 2022-03-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_title', models.CharField(max_length=200)),
                ('mod_author', models.CharField(max_length=200)),
                ('mod_source', models.CharField(max_length=200)),
                ('mod_game', models.CharField(max_length=200)),
                ('mod_description', models.TextField()),
            ],
        ),
    ]
