# Generated by Django 4.0.3 on 2022-03-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_title', models.CharField(max_length=200)),
                ('dis_author', models.CharField(default='Guest', max_length=100)),
                ('dis_date', models.DateTimeField(auto_now=True, null=True)),
                ('dis_type', models.CharField(choices=[('General', 'General'), ('Game', 'Game'), ('Mod', 'Mod')], max_length=7)),
                ('dis', models.TextField()),
                ('dis_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_author', models.CharField(default='Guest', max_length=100)),
                ('rep_title', models.CharField(max_length=200)),
                ('rep_date', models.DateTimeField(auto_now=True, null=True)),
                ('rep', models.TextField()),
                ('rep_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mods.discussion')),
            ],
        ),
    ]
